Typechecker
DATP4G6/sct pull request #160
Opened 2024-04-05 12:20 UTC by Thomast2001

closes #86 closes #122 closes #146 closes #145 closes #118 closes #121 closes #147 closes #148 closes #115 closes #79 closes #119 closes #107 closes #117 closes #76

please review this very short pull request

2024-04-08 10:08 UTC, Bliztle requested changes
There is a general inconsitency in the usage of TypeTable.None and TypeTable.Void, where a lot of voids should be none, for nodes returning no type.

2024-04-08 10:41 UTC, TheMagzuz commented on SocietalConstructionTool/Compiler/Typechecker/SctTypeChecker.cs
> +                _errors.Add(new CompilerError("Literal type not recognized, must be int or float.", context.Start.Line, context.Start.Column));
Maybe also exception?

2024-04-08 10:41 UTC, TheMagzuz commented on SocietalConstructionTool/Compiler/Typechecker/SctTypeChecker.cs
> +                    _errors.Add(new CompilerError($"Variable {id.GetText()} does not exist in agent {agentName}", context.Start.Line, context.Start.Column));
Field instead of variable?

2024-04-08 10:41 UTC, TheMagzuz commented on SocietalConstructionTool/Compiler/Typechecker/VtableEntry.cs
> +        }
Primary constructor

2024-04-08 11:46 UTC, Tinggaard commented
> There is a general inconsitency in the usage of TypeTable.None and TypeTable.Void, where a lot of voids should be none, for nodes returning no type.

This should be fixed now

2024-04-09 09:10 UTC, Bliztle approved these changes

2024-04-09 09:13 UTC, Bliztle approved these changes

2024-04-09 09:14 UTC, merged