If statements added
DATP4G6/sct pull request #47
Opened 2024-03-18 13:57 UTC by MetteLarsen

closes #6

2024-03-19 08:25 UTC, Bliztle requested changes

2024-03-19 08:25 UTC, Bliztle commented on SocietalConstructionTool/Compiler/SctTranslator.cs
> +            //var expressionNode = _stack.Pop();
remove comment

2024-03-19 08:25 UTC, Bliztle commented on SocietalConstructionTool/Compiler/SctTranslator.cs
> +            // var expressionNode = _stack.Pop();
remove comment

2024-03-19 08:25 UTC, Bliztle commented on SocietalConstructionTool/Compiler/SctTranslator.cs
> +            var childBlockNode = _stack.Pop();
Refactor all this to a single function returning the IfSyntaxDeclaration `@if`, reducing `ExitIf` and `ExitIfElse` to being only a call to that function and pushing to stack, with `ExitIfElse` wrapping in the else block as done currently.

Current implementation repeats a lot of code.

2024-03-21 08:41 UTC, Tinggaard approved these changes

2024-03-21 08:43 UTC, Bliztle approved these changes

2024-03-21 08:43 UTC, merged