Unary minus and logical not expression
DATP4G6/sct pull request #63
Opened 2024-03-20 13:46 UTC by Thomast2001

closes #20 

logical not:
expression != 0 ? 0:1

2024-03-20 14:24 UTC, TheMagzuz approved these changes

2024-03-20 14:25 UTC, Tinggaard requested changes

2024-03-20 14:25 UTC, Tinggaard commented on SocietalConstructionTool/Compiler/SctTranslator.cs
> +            var expression = (ExpressionSyntax)_stack.Pop();
Use new pop with cast infered

2024-03-21 08:59 UTC, Tinggaard approved these changes

2024-03-21 09:03 UTC, MetteLarsen approved these changes

2024-03-21 09:03 UTC, merged