added exit statement
DATP4G6/sct pull request #71
Opened 2024-03-21 09:52 UTC by MetteLarsen

solved #42

2024-03-21 10:45 UTC, Tinggaard requested changes

2024-03-21 10:45 UTC, Tinggaard commented on SocietalConstructionTool/Compiler/SctTranslator.cs
> +using Antlr4.Runtime.Atn;
Remove :)

2024-03-22 08:22 UTC, Tinggaard approved these changes

2024-03-22 08:25 UTC, TheMagzuz approved these changes

2024-03-22 08:25 UTC, merged